### ISSUE TITLE
Nexradlevel2 open_datatree returns wrong datasets when passing sweeps argument

### ISSUE THREAD

**Issue by aladinor** [openradar/xradar#239]
* xradar version: 0.8.0
* Python version: 3.12
* Operating System:

### What I Did
I opened a NEXRAD file and printed the shape for the reflectivity at different sweeps as follows.

```python
import xradar as xd
from open_radar_data import DATASETS

filename = DATASETS.fetch("KATX20130717_195021_V06")
radar= xd.io.open_nexradlevel2_datatree(filename)
print(list(radar.match("sweep_*")))
print(radar["sweep_0"].DBZH.shape)
print(radar["sweep_1"].DBZH.shape)
print(radar["sweep_2"].DBZH.shape)
print(radar["sweep_5"].DBZH.shape)
print(radar["sweep_7"].DBZH.shape)

['sweep_0', 'sweep_1', 'sweep_2', 'sweep_3', 'sweep_4', 'sweep_5', 'sweep_6', 'sweep_7', 'sweep_8', 'sweep_9', 'sweep_10', 'sweep_11', 'sweep_12', 'sweep_13', 'sweep_14', 'sweep_15']
(720, 1832)
(720, 1192)
(720, 1676)
(360, 1112)
(360, 800)

```
Then, if passing the sweeps into the `open_nexradlevel2_datatree` got an error because sweeps 5 and 7 will be renamed as 3 and 4 

```python 

filename = DATASETS.fetch("KATX20130717_195021_V06")
radar = xd.io.open_nexradlevel2_datatree(filename, sweep=[0, 1, 2, 5, 7])
print(list(radar.match("sweep_*")))
print(radar["sweep_0"].DBZH.shape)
print(radar["sweep_1"].DBZH.shape)
print(radar["sweep_2"].DBZH.shape)
print(radar["sweep_5"].DBZH.shape)
print(radar["sweep_7"].DBZH.shape)
['sweep_0', 'sweep_1', 'sweep_2', 'sweep_3', 'sweep_4']
(720, 1832)
(720, 1192)
(720, 1676)

Traceback (most recent call last):
  File "/snap/pycharm-community/425/plugins/python-ce/helpers/pydev/pydevd.py", line 1570, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/pycharm-community/425/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/alfonso/drive/Alfonso/python/xradar/delete.py", line 188, in <module>
    main()
  File "/media/alfonso/drive/Alfonso/python/xradar/delete.py", line 177, in main
    open_nexrad()
  File "/media/alfonso/drive/Alfonso/python/xradar/delete.py", line 157, in open_nexrad
    print(radar["sweep_5"].DBZH.shape)
          ~~~~~^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xarray/core/datatree.py", line 924, in __getitem__
    return self._get_item(path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xarray/core/treenode.py", line 564, in _get_item
    raise KeyError(f"Could not find node at {path}")
KeyError: 'Could not find node at sweep_5'

```

I guess the expected output for this should be 

```python 
["sweep_0", "sweep_1", "sweep_2", "sweep_5", "sweep_7", ]
```

**Comment by aladinor** [comment]
closed as completed via #240
