### ISSUE TITLE
Corrupted NexRad File?

### ISSUE THREAD

**Issue by aladinor** [openradar/xradar#245]
* xradar version: 0.8.0
* Python version: 3.12
* Operating System: Ubuntu 2404

I am trying to open a Nexrad file as follows

```python 
import fsspec
import xradar as xd

file = "s3://noaa-nexrad-level2/2023/06/29/KILX/KILX20230629_124851_V06"
local_file = fsspec.open_local(
        f"simplecache::s3://{file}",
        s3={"anon": True},
        filecache={"cache_storage": "."},
    )
dtree = xd.io.open_nexradlevel2_datatree(local_file)
```

However, I got the following error
<details>
<summary>Click to expand the error trace</summary>

```python 
Traceback (most recent call last):
  File "/media/alfonso/drive/Alfonso/python/raw2zarr/delete.py", line 10, in <module>
    dtree = xd.io.open_nexradlevel2_datatree(local_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 1619, in open_nexradlevel2_datatree
    sweep_dict = open_sweeps_as_dict(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 1681, in open_sweeps_as_dict
    group_ds = store_entrypoint.open_dataset(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xarray/backends/store.py", line 43, in open_dataset
    vars, attrs = filename_or_obj.load()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xarray/backends/common.py", line 231, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
                                              ^^^^^^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 1411, in get_variables
    for k, v in self.ds["sweep_data"].items()
                ^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 1331, in ds
    return self._acquire()
           ^^^^^^^^^^^^^^^
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 1325, in _acquire
    root.get_sweep(self._group)
  File "/home/alfonso/mambaforge/envs/raw2zarr/lib/python3.12/site-packages/xradar/io/backends/nexrad_level2.py", line 493, in get_sweep
    moments = self.msg_31_data_header[sweep_number]["msg_31_data_header"].keys()
              ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
IndexError: list index out of range
```
</details>

When debugging, I noticed that the file contains data, but sweep # 16 (the last one) is causing the error. 

Any thoughts on this?

**Comment by kmuehlbauer** [comment]
@aladinor Not sure, maybe a iteration problem, starting with 1 instead of zero. Or similar?

**Comment by aladinor** [comment]
Hi @kmuehlbauer, 

No, when reading the number elevations the file says that there are 17 sweeps

https://github.com/openradar/xradar/blob/b4684faca3f9b91717571e230f47f38edcde12d9/xradar/io/backends/nexrad_level2.py#L1612C14-L1612C57

```python
nsweeps = nex.msg_5["number_elevation_cuts"]
print(nsweeps)

17
```

**Comment by kmuehlbauer** [comment]
Then maybe one elevation is skipped during the process or overwritten?

**Comment by aladinor** [comment]
Well, actually VCP-212 should only contain 14 elevations according to Rauber & Nesbitt 2018. 


![VCPS-nexrad](https://github.com/user-attachments/assets/917ebe2a-e03f-431d-8c5e-0101668c3398)
 
But VCP-212 file contains 17. What I can notice is that there might be some duplicated sweeps as showing here

<details>
<summary>sweeps</summary>

```python

print(ex.msg_5["elevation_data"])

[OrderedDict([('elevation_angle', 0.4833984375),
              ('channel_config', 2),
              ('waveform_type', 1),
              ('super_resolution', 11),
              ('prf_number', 1),
              ('prf_pulse_count', 15),
              ('azimuth_rate', 15400),
              ('ref_thresh', 16),
              ('vel_thresh', 16),
              ('sw_thresh', 16),
              ('zdr_thres', 16),
              ('phi_thres', 16),
              ('rho_thres', 16),
              ('edge_angle_1', 0),
              ('dop_prf_num_1', 0),
              ('dop_prf_pulse_count_1', 0),
              ('edge_angle_2', 0),
              ('dop_prf_num_2', 0),
              ('dop_prf_pulse_count_2', 0),
              ('edge_angle_3', 0),
              ('dop_prf_num_3', 0),
              ('dop_prf_pulse_count_3', 0)]),
 OrderedDict([('elevation_angle', 0.4833984375),
              ('channel_config', 2),
              ('waveform_type', 2),
              ('super_resolution', 7),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 10528),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 64),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 64),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 64)]),
 OrderedDict([('elevation_angle', 0.87890625),
              ('channel_config', 2),
              ('waveform_type', 1),
              ('super_resolution', 11),
              ('prf_number', 1),
              ('prf_pulse_count', 15),
              ('azimuth_rate', 15400),
              ('ref_thresh', 16),
              ('vel_thresh', 16),
              ('sw_thresh', 16),
              ('zdr_thres', 16),
              ('phi_thres', 16),
              ('rho_thres', 16),
              ('edge_angle_1', 0),
              ('dop_prf_num_1', 0),
              ('dop_prf_pulse_count_1', 0),
              ('edge_angle_2', 0),
              ('dop_prf_num_2', 0),
              ('dop_prf_pulse_count_2', 0),
              ('edge_angle_3', 0),
              ('dop_prf_num_3', 0),
              ('dop_prf_pulse_count_3', 0)]),
 OrderedDict([('elevation_angle', 0.87890625),
              ('channel_config', 2),
              ('waveform_type', 2),
              ('super_resolution', 7),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 10528),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 64),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 64),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 64)]),
 OrderedDict([('elevation_angle', 1.318359375),
              ('channel_config', 2),
              ('waveform_type', 1),
              ('super_resolution', 11),
              ('prf_number', 2),
              ('prf_pulse_count', 15),
              ('azimuth_rate', 16768),
              ('ref_thresh', 16),
              ('vel_thresh', 16),
              ('sw_thresh', 16),
              ('zdr_thres', 16),
              ('phi_thres', 16),
              ('rho_thres', 16),
              ('edge_angle_1', 0),
              ('dop_prf_num_1', 0),
              ('dop_prf_pulse_count_1', 0),
              ('edge_angle_2', 0),
              ('dop_prf_num_2', 0),
              ('dop_prf_pulse_count_2', 0),
              ('edge_angle_3', 0),
              ('dop_prf_num_3', 0),
              ('dop_prf_pulse_count_3', 0)]),
 OrderedDict([('elevation_angle', 1.318359375),
              ('channel_config', 2),
              ('waveform_type', 2),
              ('super_resolution', 7),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 10528),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 64),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 64),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 64)]),
 OrderedDict([('elevation_angle', 1.8017578125),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 3),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 19216),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 26),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 26),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 26)]),
 OrderedDict([('elevation_angle', 2.4169921875),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 4),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 19904),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 26),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 26),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 26)]),
 OrderedDict([('elevation_angle', 3.1201171875),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 5),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 20552),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 26),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 26),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 26)]),
 OrderedDict([('elevation_angle', 3.9990234375),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 6),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 19224),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 27),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 27),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 27)]),
 OrderedDict([('elevation_angle', 5.09765625),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 6),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 19224),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 28),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 28),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 28)]),
 OrderedDict([('elevation_angle', 6.416015625),
              ('channel_config', 0),
              ('waveform_type', 4),
              ('super_resolution', 14),
              ('prf_number', 6),
              ('prf_pulse_count', 3),
              ('azimuth_rate', 19224),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 4),
              ('dop_prf_pulse_count_1', 28),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 4),
              ('dop_prf_pulse_count_2', 28),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 4),
              ('dop_prf_pulse_count_3', 28)]),
 OrderedDict([('elevation_angle', 7.998046875),
              ('channel_config', 0),
              ('waveform_type', 3),
              ('super_resolution', 10),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 20696),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 6),
              ('dop_prf_pulse_count_1', 38),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 6),
              ('dop_prf_pulse_count_2', 38),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 6),
              ('dop_prf_pulse_count_3', 38)]),
 OrderedDict([('elevation_angle', 10.01953125),
              ('channel_config', 0),
              ('waveform_type', 3),
              ('super_resolution', 10),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 20688),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 7),
              ('dop_prf_pulse_count_1', 41),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 7),
              ('dop_prf_pulse_count_2', 41),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 7),
              ('dop_prf_pulse_count_3', 41)]),
 OrderedDict([('elevation_angle', 12.48046875),
              ('channel_config', 0),
              ('waveform_type', 3),
              ('super_resolution', 10),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 20928),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 8),
              ('dop_prf_pulse_count_1', 44),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 8),
              ('dop_prf_pulse_count_2', 44),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 8),
              ('dop_prf_pulse_count_3', 44)]),
 OrderedDict([('elevation_angle', 15.6005859375),
              ('channel_config', 0),
              ('waveform_type', 3),
              ('super_resolution', 10),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 20928),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 8),
              ('dop_prf_pulse_count_1', 44),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 8),
              ('dop_prf_pulse_count_2', 44),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 8),
              ('dop_prf_pulse_count_3', 44)]),
 OrderedDict([('elevation_angle', 19.51171875),
              ('channel_config', 0),
              ('waveform_type', 3),
              ('super_resolution', 10),
              ('prf_number', 0),
              ('prf_pulse_count', 0),
              ('azimuth_rate', 20928),
              ('ref_thresh', 28),
              ('vel_thresh', 28),
              ('sw_thresh', 28),
              ('zdr_thres', 28),
              ('phi_thres', 28),
              ('rho_thres', 28),
              ('edge_angle_1', 5464),
              ('dop_prf_num_1', 8),
              ('dop_prf_pulse_count_1', 44),
              ('edge_angle_2', 38232),
              ('dop_prf_num_2', 8),
              ('dop_prf_pulse_count_2', 44),
              ('edge_angle_3', 60984),
              ('dop_prf_num_3', 8),
              ('dop_prf_pulse_count_3', 44)])]
```
<details>

we can notice that  `0.4833984375`, `0.87890625`, and ` 1.318359375` fixed_angles are duplicated

**Comment by kmuehlbauer** [comment]
Can we extract those additional sweeps somehow? It seems that the iteration process is somehow broken, right?

**Comment by aladinor** [comment]
yeah. But the question here is, how should we label the repeated sweep? any thoughts on this @mgrover1

**Comment by kmuehlbauer** [comment]
I'd label them in the order they are read from the file.

**Comment by aladinor** [comment]
It could be a solution, but I am working on the [raw2zarr](https://github.com/aladinor/raw2zarr) pipeline to append/convert NEXRAD data into a time series. Thus, this new sweep won't match this schema, where every sweep should correspond to those mentioned/shown in Figure 10.5 in Rauber & Nesbitt (2018).

**Comment by kmuehlbauer** [comment]
It might be that these three double sweeps are somehow combined in that image? Would it make sense to read the data as is, enumerating the sweeps as they ordered in the file and after that make the comparison by the metadata?

**Comment by aladinor** [comment]
I was thinking of creating a new dimension and appending the duplicated sweep, but also metadata could be a good idea. Let me check it out.

**Comment by syedhamidali** [comment]
@aladinor, how have you not come across this until now?

Here’s a discussion about the scan strategy: [Google Groups - PyART Users](https://groups.google.com/g/pyart-users/c/3hrHwDZGZQo/m/KEFLKRfyAwAJ).

Additionally, I had a conversation last year with Dr. Robin Tanamachi, who explained (and I quote):
You’re looking at “split cut” data with two different pulse repetition frequencies – one (CS) for long range and the other (CD) for high Doppler velocity. They don’t “stack” (i.e., can’t be combined into the same radar data file) because they have different maximum ranges (and hence, array sizes).

That explanation was specific to PyART.

I’m currently using the workaround provided below.

```python
def combine_sweeps(dtree):
    from xarray import DataTree

    dtree_copy = dtree.copy(deep=True)
    sweep_groups = {}

    # Group sweeps by their fixed angle
    for swp in dtree.match("sweep_*"):
        ds = dtree[swp].to_dataset()
        angle = ds.sweep_fixed_angle.values.item()
        if angle not in sweep_groups:
            sweep_groups[angle] = []
        sweep_groups[angle].append((swp, ds))

    # Create a new DataTree to store combined sweeps in sorted order
    new_dtree = DataTree()

    # Process each group with matching angles
    for angle, sweeps in sweep_groups.items():
        if len(sweeps) == 1:
            # Add single sweep nodes directly to the new DataTree
            swp, ds = sweeps[0]
            new_dtree[swp] = DataTree(ds)
            continue

        # Sort sweeps by range dimension size in descending order
        sweeps = sorted(sweeps, key=lambda x: x[1].sizes['range'], reverse=True)

        # The largest range dataset is the primary dataset
        primary_swp, primary_ds = sweeps[0]

        for secondary_swp, secondary_ds in sweeps[1:]:  # Process smaller range datasets
            # Align secondary dataset to the primary dataset's range
            aligned_secondary_ds = secondary_ds.reindex_like(primary_ds, method="nearest")

            # Rename variables in the secondary dataset to avoid overwrites
            if 'DBZH' in aligned_secondary_ds:
                aligned_secondary_ds = aligned_secondary_ds.rename({'DBZH': 'DBZH_SHORT'})

            # Merge aligned secondary dataset into the primary dataset
            primary_ds = xr.merge([primary_ds, aligned_secondary_ds], compat='override')

        # Add the combined dataset to the new DataTree
        new_dtree[primary_swp] = DataTree(primary_ds)

    # Reassign sweep numbers in sorted order
    sweeps_sorted = sorted(
        [key for key in new_dtree.groups if key.startswith('/sweep_')],
        key=lambda k: int(k.split('_')[-1])
    )

    ordered_dtree = DataTree()
    for new_index, swp in enumerate(sweeps_sorted):
        # Update the sweep_number and reassign the node to maintain order
        ds = new_dtree[swp].to_dataset()
        ds = ds.assign_coords(sweep_number=new_index)
        ordered_dtree[f"/sweep_{new_index}"] = DataTree(ds)

    # Copy other nodes (non-sweeps) back to the new DataTree
    for key in dtree.groups:
        if not key.startswith('/sweep_') and key != '/':
            ordered_dtree[key] = dtree_copy[key]

    return ordered_dtree
```

**Comment by aladinor** [comment]
Thanks @syedhamidali for sharing this.  I think we can fix this within `xradar`. However, this needs to be considered in [raw2zarr](https://github.com/aladinor/raw2zarr) pipeline
